// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngcetnnrhwgbjdfeiaju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nY2V0bm5yaHdnYmpkZmVpYWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTYwODEsImV4cCI6MjA3MjI5MjA4MX0.YKbX-RRqUDRAqFgt8q0RAo099js5huYBx8508Kt8-CQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});